[package]
name = "substrate-runtime-fuzzer"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
resolver = "2"
members = [
    "kitchensink",
    "kusama",
    "solochain",
    "asset-hub-kusama",
]