name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always
  SKIP_WASM_BUILD: 1

jobs:
  run-fmt-and-clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup default stable
      - run: rustup component add rustfmt clippy
#      - uses: Swatinem/rust-cache@v2
      - name: Run fmt
        run: cargo fmt --check --manifest-path runtimes/Cargo.toml
        run: cargo fmt --check --manifest-path templates/Cargo.toml
      - name: Run clippy
        run: cargo clippy -q --workspace --no-deps --manifest-path runtimes/Cargo.toml -- -D clippy::pedantic
        run: cargo clippy -q --workspace --no-deps --manifest-path templates/Cargo.toml -- -D clippy::pedantic
