name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always
  SKIP_WASM_BUILD: 1

jobs:
  run-fmt-and-clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup default nightly
      - uses: Swatinem/rust-cache@v2
      - name: Run fmt
        run: cargo fmt --check
      - name: Run clippy
        run: cargo clippy --workspace -- -D clippy::pedantic
